version: '3.3'
services:
  db:
    image: postgres:15.6
    container_name: postgres
    environment:
      POSTGRES_DATABASE: 'db_s'
      POSTGRES_USER: 'joao'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_ROOT_PASSWORD: 'root'
    ports:
      - '5432:5432'